### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by russss** [russss/datasette-geo#4]
Blockers:

* [ ] merge simonw/datasette#437
* [x] merge simonw/datasette#441
* [ ] merge simonw/datasette#443
* [ ] Fix #1 
* [ ] Fix #2 (probably)

**Comment by simonw** [comment]
https://github.com/simonw/datasette/pull/441 is now merged
